### ISSUE TITLE
Em list.c

### ISSUE THREAD

**Issue by fspacheco** [jaici/projetoListaGit#3]
Linha 7: o retorno é um ponteiro NULL para Lst.

(Estás usando doxygen?)

L. 28: corrigir "ligacao"

L. 41: troque a ordem das linhas 40 e 41, para manter o teste do ponteiro FP "colado" a sua criação.

L. 61: a ideia com insert2 é que insert1 seja descartada. Seria melhor refazer a função.

L. 68: atualizar a descrição, informando que o retorno é NULL se não for encontrado

_L. 106: IMPORTANTE_: onde está liberação de memória?

L. 123: corrigir "ocupado"

L. 148: armazena elemento anterior, não lista, ok?

L. 220: Aqui também faltou liberar a memória do elemento

**Comment by fspacheco** [comment]
Valgrind está dando a seguinte mensagem:
==6574== Invalid read of size 4
==6574==    at 0x80495B0: freeMemoryDuoList (list.c:270)
==6574==    by 0x804892C: main (main.c:23)
==6574==  Address 0x4587070 is 8 bytes inside a block of size 12 free'd
==6574==    at 0x402B06C: free (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==6574==    by 0x80495C0: freeMemoryDuoList (list.c:271)
==6574==    by 0x8048920: main (main.c:22)

Acho que está relacionado a não ter liberado a memória dentro da função removeDuoList()

Compile com -g e execute
valgrind --tool=memcheck --leak-check=yes ./projlista

**Comment by jaici** [comment]
realizada correção no arquivo conforme solicitado.
