### ISSUE TITLE
Em listAllegro.c

### ISSUE THREAD

**Issue by fspacheco** [jaici/projetoListaGit#5]
L. 37 e 38: como tu ainda não sabe o tipo do elemento, ficou forçado igualar o ponteiro a aux->info. Melhor inicializar com NULL.

L. 91: "espessura" da borda

L. 121: faltou o cálculo

L. 128: os comentários estão duplicados

L. 134-135: mesmo comentário a respeito da atribuição das linhas 37-38

**Comment by jaici** [comment]
Realizada alterações informadas.
